persistence:
  enabled: true
  size: 50Gi

service:
  name: docker-registry
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30606

extraEnvVars:
  - name: OTEL_TRACES_EXPORTER
    value: "none"
  - name: OTEL_METRICS_EXPORTER
    value: "none"
