apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-controller

resources:
  - release.yaml

configMapGenerator:
  - name: nginx-values
    files:
      - values.yaml

secretGenerator:
  - name: nginx-secrets
    files:
      - encrypted.yaml
