controller:
  hostNetwork: false
  allowSnippetAnnotations: true
  # dnsPolicy: CLusterFirstWithHostNet

  extraArgs:
    default-ssl-certificate: "ingress-controller/tls-cert"

service:
  enabled: true
  type: ClusterIP
