grafana:
    adminUser: ENC[AES256_GCM,data:6HS/PkM=,iv:UTuk53GZ4jW9MjIZqfEFGC84P8UQcpjqXQfQFCpyWyE=,tag:a2OMsqLY/uRtk0NRVRyuFg==,type:str]
    adminPassword: ENC[AES256_GCM,data:kZgKYKPqR5S5,iv:eyvi3jBZb+tOrqd8VfD7xy/WQ0ubQCDZJgy2JLQX8MA=,tag:5tJcYRLKau7CkxuPpYOlcA==,type:str]
sops:
    age:
        - recipient: age1nhn8dadwmzsjw4jztasxy88pk66y3fw087u8uquvg79vfrnckpkqdq5rrh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZkhNODhyemhMOE9ra0s2
            dDk0aHpQa3M3enlPdnFmb1V6b0RKcjJ0TGd3ClgrOURjcWVZY2tpTzhKOUNBVEEr
            WjdoNzlPRXZkUy9hYjlzY3NJTXFTcVEKLS0tIHhoOGI1QWVJYk55MmV6cmJodmlx
            c2FQK2FLOHlkM1ZVWXZSNU1XSFMwT2MKONJRML3sy6bGURtjQ6/PEeDIJ+gIIcaH
            JOuHfnwuJuU3VnBliC4pB6u8wFNeaNqnS9GxZj7yCrmRFAgRGDPaww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T17:20:06Z"
    mac: ENC[AES256_GCM,data:S9BJsQkesHfnvmihydSE9cUXzgrHmgPAmRhXnrFWZ6R5xBcBAyq4E5s/+fGKlOLw4D6YvO6QYkQgWV5a/EmPRMP/0ZN1uz0TX7KT799+qIKpHjrWkfyHSWE5CEKlWeMRAg/K8w2tA5wNsR85Zxn2abbie/2sQlm1zhZnacbzKBY=,iv:BRaSlCga8yF5888543m114epva3dE+x1+d2u6YjO1Tw=,tag:fFf48z6FYK0ZzqPYRfXLtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
