repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

releases:
  - name: grafana
    namespace: monitoring
    chart: prometheus/kube-prometheus-stack
    version: 80.10.x
    values:
      - ./values.yaml
    secrets:
      - ./encrypted.yaml
