apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - release.yaml

configMapGenerator:
  - name: grafana-values
    files:
      - values.yaml

secretGenerator:
  - name: grafana-secrets
    files:
      - encrypted.yaml
