name: GitOps Docker

on:
  push:
    paths:
      - 'apps/**'

env:
  DOCKER_REGISTRY: "docker-registry:5000"

jobs:
  prepare:
    runs-on: arc-runner-set
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      run_build: ${{ steps.set-matrix.outputs.run_build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed folders
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          dir_names: true
          files: apps/**

      - name: Generate Matrix JSON
        id: set-matrix
        run: |
          folders="${{ steps.changed-files.outputs.all_changed_files }}"
          if [ -z "$folders" ]; then
            echo "run_build=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          JSON_ARRAY="[]"
          for folder in $folders; do
            IMG_NAME=$(grep 'name=' "$folder/application.conf" | cut -d'=' -f2 | xargs)
            IMG_TAG=$(grep 'version=' "$folder/application.conf" | cut -d'=' -f2 | xargs)

            JSON_ARRAY=$(echo "$JSON_ARRAY" | jq -c ". += [{\"path\": \"$folder\", \"name\": \"$IMG_NAME\", \"tag\": \"$IMG_TAG\"}]")
          done

          echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT
          echo "run_build=true" >> $GITHUB_OUTPUT


  build:
    needs: prepare
    if: needs.prepare.outputs.run_build == 'true'
    runs-on: arc-runner-set
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Prepare docker instance
        run: |
          sudo mkdir -p /etc/docker
          echo '{ "insecure-registries":["${{DOCKER_REGISTRY}}"] }' | sudo tee /etc/docker/daemon.json
          sudo kill -SIGHUP $(pidof dockerd)
          sleep 2
          docker info | grep -A 3 "Insecure Registries"

      - name: Build Docker Image
        run: |
          docker build -t ${{ matrix.name }}:${{ matrix.tag }} ./${{ matrix.path }}

      - name: Export and Import to cluster registry
        run: |
          docker push ${{DOCKER_REGISTRY}}/${{ matrix.name }}:${{ matrix.tag }}

      - name: List current images - testing only
        run: |
          sudo k3s ctr images list | grep ${{ matrix.name }}
