name: GitOps Docker

on:
  push:
    paths:
      - 'apps/**'

jobs:
  prepare:
    runs-on: arc-runner-set
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare builds
        id: set-matrix
        run: |
          DIFF=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^middleware/' | cut -d/ -f2 | sort -u || true)
          JSON_ARRAY=$(echo "$DIFF" | jq -R . | jq -s -c .)
          echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    if: needs.prepare.outputs.matrix != '[]'

    runs-on: arc-runner-set
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        env:
          CHART_NAME: ${{ matrix.chart }}
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_SECRET_KEY }}
        run: |
          echo "Building docker"
